### PR TITLE
Add a getOrLoadChat method

### PR DESCRIPTION
**Pull request by ctian1**

### CODE REVIEW

**Comment by samczsun** [comment]
My apologies for this inconvenience, but to ensure legalities are met, you must agree with the Contributor License Agreement. Thank you

**Comment by ctian1** [comment]
Alright.. how would I go about signing this CLA?

**Comment by samczsun** [comment]
You can use a digital signature in the format of `/Your Name/` or `/s/Your Name`

**Comment by ctian1** [comment]
@samczsun what do you mean?

**Pull request merged**
